// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZ7yeodZdCqOpKnAqPqylqAKtQSAbE4w',
    appId: '1:525189697695:web:6512b6063f5c21837f12aa',
    messagingSenderId: '525189697695',
    projectId: 'ippu-20dbc',
    authDomain: 'ippu-20dbc.firebaseapp.com',
    storageBucket: 'ippu-20dbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_Cu0SEjqNO3PA-1_bqdDycnGX2BKFuc',
    appId: '1:525189697695:android:31f7e3b752196ce07f12aa',
    messagingSenderId: '525189697695',
    projectId: 'ippu-20dbc',
    storageBucket: 'ippu-20dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoN4YMaCyGt6IJE0x566aWxFgErbEfpQ',
    appId: '1:525189697695:ios:807f423f1ff043cd7f12aa',
    messagingSenderId: '525189697695',
    projectId: 'ippu-20dbc',
    storageBucket: 'ippu-20dbc.appspot.com',
    iosBundleId: 'com.impact.ippu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyoN4YMaCyGt6IJE0x566aWxFgErbEfpQ',
    appId: '1:525189697695:ios:a6d6216c55bd557d7f12aa',
    messagingSenderId: '525189697695',
    projectId: 'ippu-20dbc',
    storageBucket: 'ippu-20dbc.appspot.com',
    iosBundleId: 'com.example.ippu',
  );
}
